name: Main

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '*.md'
    branches:
      - main

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-nightly-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
          rust-version: nightly
      - run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-stable-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
      - run: cargo clippy --all-targets --all-features -- -D clippy::all

  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-stable-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
      - run: cargo check --locked --all

  build-example:
    needs: [codestyle, lint, compile]
    name: Build example wasm app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-1.46.0-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
            targets: wasm32-wasi
            rust-version: "1.46.0"
      - name: Build
        working-directory: tests/app
        run: cargo build --locked --release --target wasm32-wasi
      - name: Upload wasm
        uses: actions/upload-artifact@v1
        with:
            name: wasm-module
            path: tests/app/target/wasm32-wasi/release/app.wasm

  test:
    needs: [build-example]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Download wasm
      uses: actions/download-artifact@v1
      with:
          name: wasm-module
          path: tests/app/target/wasm32-wasi/release
    - name: Test
      run: cargo test --locked

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [test]
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-musl
            bin: 'fasttime'
            name: 'fasttime-Linux-x86_64.tar.gz'
          - os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
            bin: 'fasttime.exe'
            name: 'fasttime-Windows-x86_64.zip'
          - os: macOS-latest
            rust: stable
            target: x86_64-apple-darwin
            bin: 'fasttime'
            name: 'fasttime-Darwin-x86_64.tar.gz'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
        targets: ${{ matrix.target }}
    - name: Setup musl-gcc
      if: contains(matrix.target, 'musl')
      run: |
        sudo apt-get install musl-tools
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --locked --release --target ${{ matrix.target }}
    - name: Package
      shell: bash
      run: |
        strip target/${{ matrix.target }}/release/${{ matrix.bin }}
        cd target/${{ matrix.target }}/release
        if [[ "${{ matrix.os }}" == "windows-latest" ]]
        then
          7z a ../../../${{ matrix.name }} ${{ matrix.bin }}
        else
          tar czvf ../../../${{ matrix.name }} ${{ matrix.bin }}
        fi
        cd -
    - name: Publish
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: 'fasttime*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Brew Bump
      if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'macos-latest' && env.HOMEBREW_GITHUB_API_TOKEN
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
      run: |
        SHA256=$(shasum -a 256 ${{ matrix.name }} | awk '{printf $1}')
        VERSION=${GITHUB_REF#refs/tags/}
        echo "SHA256 ${SHA256}"
        echo "VERSION ${VERSION}"
        brew tap softprops/tools
        brew bump-formula-pr \
          -f \
          --version=${VERSION} \
          --no-browse \
          --no-audit \
          --sha256=${SHA256} \
          --url="https://github.com/softprops/fasttime/releases/download/${VERSION}/${{ matrix.name }}" \
          softprops/tools/fasttime

  publish-crate:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v1
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/') && env.CRATES_TOKEN
        shell: bash
        run: cargo publish --locked --token ${{ env.CRATES_TOKEN }}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
